// expensesNgApp/src/app/pages/expense-book-dashboard/expense-book-dashboard.component.ts
import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ExpenseBookService } from '../../services/expense-book.service';
import { AuthStateService } from '../../services/auth-state.service';
import { ToastService } from '../../services/toast.service';
import { ExpenseBook, CreateExpenseBookRequest } from '../../models/expense-book.model';
import { ButtonComponent } from '../../components/button/button.component';
import { InputComponent } from '../../components/input/input.component';
import { ModalComponent } from '../../components/modal/modal.component';
import { LoadingComponent, EmptyStateComponent, ErrorStateComponent } from '../../components/loading/loading.component';
import { formatCurrency } from '../../utils/helpers';

@Component({
  selector: 'app-expense-book-dashboard',
  standalone: true,
  imports: [CommonModule, FormsModule, ButtonComponent, InputComponent, ModalComponent, LoadingComponent, EmptyStateComponent, ErrorStateComponent],
  templateUrl: './expense-book-dashboard.component.html',
  styleUrl: './expense-book-dashboard.component.css'
})
export class ExpenseBookDashboardComponent implements OnInit {
  books = signal<ExpenseBook[]>([]);
  loading = signal(true);
  error = signal('');
  showCreateModal = signal(false);
  showDeleteModal = signal(false);
  bookToDelete = signal<ExpenseBook | null>(null);
  createLoading = false;
  deleteLoading = false;
  createError = '';
  createForm: CreateExpenseBookRequest = { name: '', description: '', currency: 'USD', icon: '📖' };

  private bookService = inject(ExpenseBookService);
  private auth = inject(AuthStateService);
  private toast = inject(ToastService);
  private router = inject(Router);

  ngOnInit() { this.loadBooks(); }

  async loadBooks() {
    this.loading.set(true);
    this.error.set('');
    try {
      const res = await this.bookService.getExpenseBooks();
      if (res.success) this.books.set(res.data || []);
      else this.error.set(res.error || 'Failed to load expense books');
    } catch (e: any) { this.error.set(e.message || 'Failed to load'); }
    finally { this.loading.set(false); }
  }

  navigateToBook(book: ExpenseBook) {
    this.router.navigate([`/${book.id}/dashboard`]);
  }

  openCreateModal() { this.createForm = { name: '', description: '', currency: 'USD', icon: '📖' }; this.createError = ''; this.showCreateModal.set(true); }
  closeCreateModal() { this.showCreateModal.set(false); }

  async handleCreate() {
    this.createError = '';
    if (!this.createForm.name.trim()) { this.createError = 'Book name is required'; return; }
    this.createLoading = true;
    try {
      const res = await this.bookService.createExpenseBook(this.createForm);
      if (res.success && res.data) {
        this.books.update(b => [...b, res.data!]);
        this.toast.success('Expense book created');
        this.closeCreateModal();
      } else { this.createError = res.error || 'Failed to create'; }
    } catch (e: any) { this.createError = e.message || 'Failed to create'; }
    finally { this.createLoading = false; }
  }

  openDeleteConfirm(book: ExpenseBook, event: Event) {
    event.stopPropagation();
    this.bookToDelete.set(book);
    this.showDeleteModal.set(true);
  }
  closeDeleteModal() { this.showDeleteModal.set(false); this.bookToDelete.set(null); }

  async handleDelete() {
    const book = this.bookToDelete();
    if (!book) return;
    this.deleteLoading = true;
    try {
      const res = await this.bookService.deleteExpenseBook(book.id);
      if (res.success) {
        this.books.update(b => b.filter(x => x.id !== book.id));
        this.toast.success('Expense book deleted');
        this.closeDeleteModal();
      } else { this.toast.error(res.error || 'Failed to delete'); }
    } catch (e: any) { this.toast.error(e.message || 'Failed to delete'); }
    finally { this.deleteLoading = false; }
  }

  handleLogout() { this.auth.logout(); this.router.navigate(['/login']); }
  protected readonly formatCurrency = formatCurrency;
}

<div class="page-container">
  <!-- Header -->
  <div class="page-header">
    <div class="header-left">
      <div class="logo-mark">E</div>
      <div>
        <h1 class="page-title">My Expense Books</h1>
        <p class="page-subtitle">Select a book to track expenses</p>
      </div>
    </div>
    <div class="header-actions">
      <app-button variant="ghost" (clicked)="handleLogout()">Logout</app-button>
      <app-button (clicked)="openCreateModal()">+ New Book</app-button>
    </div>
  </div>

  <!-- Loading/Error/Empty states -->
  <app-loading *ngIf="loading()" text="Loading expense books..."></app-loading>
  <app-error-state *ngIf="!loading() && error()" [message]="error()"></app-error-state>

  <!-- Books grid -->
  <div *ngIf="!loading() && !error()" class="books-section">
    <app-empty-state
      *ngIf="books().length === 0"
      title="No expense books yet"
      description="Create your first expense book to start tracking"
      icon="📚">
      <app-button (clicked)="openCreateModal()">Create First Book</app-button>
    </app-empty-state>

    <div *ngIf="books().length > 0" class="books-grid">
      <div *ngFor="let book of books()" class="book-card" (click)="navigateToBook(book)">
        <div class="book-icon" [style.background]="book.color || 'var(--gradient-primary)'">
          {{ book.icon || '📖' }}
        </div>
        <div class="book-info">
          <h3 class="book-name">{{ book.name }}</h3>
          <p class="book-description" *ngIf="book.description">{{ book.description }}</p>
          <div class="book-stats">
            <span class="stat">
              <span class="stat-label">Currency:</span>
              <span class="stat-value">{{ book.currency || 'USD' }}</span>
            </span>
          </div>
        </div>
        <button class="book-delete" (click)="openDeleteConfirm(book, $event)" title="Delete book">
          ✕
        </button>
      </div>
    </div>
  </div>

  <!-- Create Modal -->
  <app-modal [isOpen]="showCreateModal()" title="Create Expense Book" (closed)="closeCreateModal()">
    <form (ngSubmit)="handleCreate()" class="modal-form">
      <div *ngIf="createError" class="error-banner">{{ createError }}</div>
      <app-input label="Book Name" [value]="createForm.name" (valueChange)="createForm.name = $event" placeholder="e.g. Personal, Business" [required]="true"></app-input>
      <app-input label="Description (optional)" [value]="createForm.description || ''" (valueChange)="createForm.description = $event" placeholder="What is this book for?"></app-input>
      <div class="form-row">
        <app-input label="Currency" [value]="createForm.currency || 'USD'" (valueChange)="createForm.currency = $event" placeholder="USD"></app-input>
        <app-input label="Icon (emoji)" [value]="createForm.icon || ''" (valueChange)="createForm.icon = $event" placeholder="📖"></app-input>
      </div>
      <div class="modal-actions">
        <app-button type="button" variant="ghost" (clicked)="closeCreateModal()">Cancel</app-button>
        <app-button type="submit" [loading]="createLoading">Create Book</app-button>
      </div>
    </form>
  </app-modal>

  <!-- Delete Confirm Modal -->
  <app-modal [isOpen]="showDeleteModal()" title="Delete Expense Book" (closed)="closeDeleteModal()">
    <div class="delete-confirm">
      <p>Are you sure you want to delete <strong>{{ bookToDelete()?.name }}</strong>?</p>
      <p class="delete-warning">This will permanently delete all expenses in this book.</p>
      <div class="modal-actions">
        <app-button variant="ghost" (clicked)="closeDeleteModal()">Cancel</app-button>
        <app-button variant="danger" [loading]="deleteLoading" (clicked)="handleDelete()">Delete</app-button>
      </div>
    </div>
  </app-modal>
</div>

// webapps/src/pages/ExpenseBookDashboard.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/Card/Card';
import { Button } from '@/components/Button/Button';
import { Loading, EmptyState } from '@/components/Loading/Loading';
import { Modal } from '@/components/Modal/Modal';
import { Input } from '@/components/Input/Input';
import { Select } from '@/components/Select/Select';
import { useAuth } from '@/hooks/useAuth';
import { expenseBookService } from '@/services/expenseBookService';
import type { ExpenseBook, CreateExpenseBookRequest } from '@/types/expenseBook';
import styles from './ExpenseBookDashboard.module.css';

const ExpenseBookDashboard: React.FC = () => {
  const navigate = useNavigate();
  const { logout } = useAuth();
  const [expenseBooks, setExpenseBooks] = useState<ExpenseBook[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [formData, setFormData] = useState<CreateExpenseBookRequest>({
    name: '',
    description: '',
    category: 'Personal',
    isDefault: false,
  });
  const [isCustomCategory, setIsCustomCategory] = useState(false);
  const [customCategory, setCustomCategory] = useState('');

  useEffect(() => {
    loadExpenseBooks();
    loadCategories();
  }, []);

  const loadExpenseBooks = async () => {
    try {
      setLoading(true);
      const response = await expenseBookService.getExpenseBooks();
      if (response.success && response.data) {
        setExpenseBooks(response.data);
        setError(null);
      } else {
        setError(response.error || 'Failed to load expense books');
      }
    } catch (err) {
      setError('Failed to load expense books');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const loadCategories = async () => {
    try {
      const response = await expenseBookService.getCategories();
      if (response.success && response.data) {
        setCategories(response.data);
      }
    } catch (err) {
      console.error('Failed to load categories:', err);
    }
  };

  const handleCreateExpenseBook = async () => {
    try {
      const categoryToUse = isCustomCategory ? customCategory : formData.category;
      
      if (!formData.name.trim()) {
        alert('Please enter a name for the expense book');
        return;
      }

      if (isCustomCategory && !customCategory.trim()) {
        alert('Please enter a custom category');
        return;
      }

      const response = await expenseBookService.createExpenseBook({
        ...formData,
        category: categoryToUse,
      });

      if (response.success && response.data) {
        setExpenseBooks([response.data, ...expenseBooks]);
        setIsCreateDialogOpen(false);
        resetForm();

        // Navigate to the dashboard with the new expense book
        navigate(`/${response.data.id}/dashboard`);
      } else {
        alert(response.error || 'Failed to create expense book');
      }
    } catch (err) {
      console.error('Failed to create expense book:', err);
      alert('Failed to create expense book');
    }
  };

  const handleDeleteExpenseBook = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    
    if (!confirm('Are you sure you want to delete this expense book? This cannot be undone.')) {
      return;
    }

    try {
      const response = await expenseBookService.deleteExpenseBook(id);
      if (response.success) {
        setExpenseBooks(expenseBooks.filter(book => book.id !== id));
      } else {
        alert(response.error || 'Failed to delete expense book');
      }
    } catch (err: any) {
      const errorMessage = err.response?.data?.message || 'Failed to delete expense book';
      alert(errorMessage);
    }
  };

  const handleSelectExpenseBook = (bookId: string) => {
    navigate(`/${bookId}/dashboard`);
  };

  const resetForm = () => {
    setFormData({
      name: '',
      description: '',
      category: 'Personal',
      isDefault: false,
    });
    setIsCustomCategory(false);
    setCustomCategory('');
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(amount);
  };

  const getCategoryColor = (category: string) => {
    const colors: Record<string, string> = {
      Personal: '#4CAF50',
      Work: '#2196F3',
      Business: '#FF9800',
    };
    return colors[category] || '#9C27B0';
  };

  const getCreditCardGradient = (category: string) => {
    const gradients: Record<string, string> = {
      Personal: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      Work: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
      Business: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    };
    return gradients[category] || 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)';
  };

  if (loading) {
    return <Loading />;
  }

  return (
    <div className={styles.pageWrapper}>
      {/* Header */}
      <header className={styles.header}>
        <div className={styles.headerContent}>
          <div className={styles.logo}>
            <span className={styles.logoIcon}>💰</span>
            <span className={styles.logoText}>Expense Tracker</span>
          </div>
          <div className={styles.headerActions}>
            <Button variant="secondary" onClick={logout}>
              Logout
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className={styles.mainContent}>
        <div className={styles.container}>
          <div className={styles.contentHeader}>
            <div>
              <h1 className={styles.title}>My Expense Books</h1>
              <p className={styles.subtitle}>Select an expense book to manage your finances</p>
            </div>
            <Button onClick={() => setIsCreateDialogOpen(true)}>
              + Book
            </Button>
          </div>

          {error && (
            <div className={styles.error}>{error}</div>
          )}

          {expenseBooks.length === 0 ? (
            <EmptyState
              icon="📚"
              title="No Expense Books Yet"
              description="Create your first expense book to start tracking your expenses"
              action={
                <Button onClick={() => setIsCreateDialogOpen(true)} variant="primary">
                  Create Expense Book
                </Button>
              }
            />
          ) : (
            <div className={styles.grid}>
              {expenseBooks.map((book) => (
                <div
                  key={book.id}
                  className={styles.creditCard}
                  onClick={() => handleSelectExpenseBook(book.id)}
                >
                  <div className={styles.cardGradient} style={{ background: getCreditCardGradient(book.category) }}>
                    {/* Card Header with Badge */}
                    <div className={styles.creditCardHeader}>
                      <div
                        className={styles.categoryBadge}
                        style={{ backgroundColor: getCategoryColor(book.category) }}
                      >
                        {book.category}
                      </div>
                      {book.isDefault && (
                        <span className={styles.defaultBadge}>Default</span>
                      )}
                    </div>

                    {/* Card Content */}
                    <div className={styles.creditCardContent}>
                      <div className={styles.bookNameWrapper}>
                        <h3 className={styles.bookName} title={book.name}>
                          {book.name}
                        </h3>
                      </div>

                      <div className={styles.cardStats}>
                        <div className={styles.statItem}>
                          <span className={styles.statValue}>
                            {formatCurrency(book.totalExpenses)}
                          </span>
                          <span className={styles.statLabel}>Total Spent</span>
                        </div>
                        <div className={styles.statDivider}></div>
                        <div className={styles.statItem}>
                          <span className={styles.statValue}>
                            {book.expenseCount}
                          </span>
                          <span className={styles.statLabel}>
                            {book.expenseCount === 1 ? 'Expense' : 'Expenses'}
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Hover Actions */}
                    <div className={styles.creditCardActions}>
                      <button
                        className={styles.actionBtn}
                        onClick={(e) => handleDeleteExpenseBook(book.id, e)}
                        disabled={book.isDefault && expenseBooks.length === 1}
                        title="Delete Book"
                      >
                        🗑️
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className={styles.footer}>
        <div className={styles.footerContent}>
          <p>© 2026 Expense Tracker. All rights reserved.</p>
        </div>
      </footer>

      <Modal
        isOpen={isCreateDialogOpen}
        onClose={() => {
          setIsCreateDialogOpen(false);
          resetForm();
        }}
        title="Create New Expense Book"
      >
        <div className={styles.form}>
          <Input
            label="Name"
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            placeholder="e.g., Personal Expenses, Work Expenses"
            required
          />

          <div className={styles.formGroup}>
            <label htmlFor="description">Description</label>
            <textarea
              id="description"
              className={styles.textarea}
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Optional description"
              rows={3}
            />
          </div>

          {!isCustomCategory ? (
            <div className={styles.formGroup}>
              <Select
                label="Category"
                value={formData.category}
                onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                options={categories.map((category) => ({ value: category, label: category }))}
              />
              <button
                type="button"
                className={styles.linkBtn}
                onClick={() => setIsCustomCategory(true)}
              >
                + Add Custom Category
              </button>
            </div>
          ) : (
            <div className={styles.formGroup}>
              <Input
                label="Custom Category"
                value={customCategory}
                onChange={(e) => setCustomCategory(e.target.value)}
                placeholder="Enter custom category name"
              />
              <button
                type="button"
                className={styles.linkBtn}
                onClick={() => {
                  setIsCustomCategory(false);
                  setCustomCategory('');
                }}
              >
                Use Existing Category
              </button>
            </div>
          )}

          <div className={styles.modalActions}>
            <Button
              variant="secondary"
              onClick={() => {
                setIsCreateDialogOpen(false);
                resetForm();
              }}
            >
              Cancel
            </Button>
            <Button
              variant="primary"
              onClick={handleCreateExpenseBook}
              disabled={!formData.name.trim() || (isCustomCategory && !customCategory.trim())}
            >
              Create
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default ExpenseBookDashboard;
