// webapps/src/components/Sidebar/Sidebar.tsx
import { useState, useEffect } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { useBreakpoint } from '@/hooks/useMediaQuery';
import styles from './Sidebar.module.css';

interface NavItem {
  id: string;
  label: string;
  icon: string;
  path: string;
}

interface SidebarProps {
  isCollapsed?: boolean;
  onCollapsedChange?: (collapsed: boolean) => void;
}

const navItems: NavItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: '📊', path: 'dashboard' },
  { id: 'expenses', label: 'Expenses', icon: '💰', path: 'expenses' },
  { id: 'budget', label: 'Budget', icon: '🎯', path: 'budget' },
  { id: 'insights', label: 'Insights', icon: '📈', path: 'insights' },
  { id: 'settings', label: 'Settings', icon: '⚙️', path: 'settings' },
];

export const Sidebar = ({ isCollapsed = false, onCollapsedChange }: SidebarProps) => {
  const location = useLocation();
  const { bookId } = useParams<{ bookId: string }>();
  const { isMobile } = useBreakpoint();

  const toggleCollapse = () => {
    onCollapsedChange?.(!isCollapsed);
  };

  const isActive = (path: string) => {
    return location.pathname.includes(`/${path}`);
  };

  const getNavPath = (path: string) => {
    return `/${bookId}/${path}`;
  };

  return (
    <aside className={`${styles.sidebar} ${isCollapsed && !isMobile ? styles.collapsed : ''}`}>
      {!isMobile && (
        <Link to="/" className={styles['sidebar-header']} style={{ textDecoration: 'none', color: 'inherit' }}>
          <div className={styles['sidebar-logo']}>E</div>
          <h1 className={styles['sidebar-title']}>ExpenseTracker</h1>
        </Link>
      )}

      <nav className={styles['sidebar-nav']}>
        {navItems.map((item) => (
          <Link
            key={item.id}
            to={getNavPath(item.path)}
            className={`${styles['nav-item']} ${isActive(item.path) ? styles.active : ''}`}
          >
            <span className={styles['nav-item-icon']} role="img" aria-label={item.label}>
              {item.icon}
            </span>
            <span className={styles['nav-item-text']}>{item.label}</span>
          </Link>
        ))}
      </nav>

      {!isMobile && (
        <div className={styles['sidebar-footer']}>
          <button
            className={styles['collapse-button']}
            onClick={toggleCollapse}
            aria-label={isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}
          >
            {isCollapsed ? '→' : '←'}
          </button>
        </div>
      )}
    </aside>
  );
};

// expensesNgApp/src/app/components/sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router, ActivatedRoute, NavigationEnd } from '@angular/router';
import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';

interface NavItem {
  id: string;
  label: string;
  icon: string;
  path: string;
}

const NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: '📊', path: 'dashboard' },
  { id: 'expenses', label: 'Expenses', icon: '💰', path: 'expenses' },
  { id: 'budget', label: 'Budget', icon: '🎯', path: 'budget' },
  { id: 'insights', label: 'Insights', icon: '📈', path: 'insights' },
  { id: 'settings', label: 'Settings', icon: '⚙️', path: 'settings' },
];

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.css'
})
export class SidebarComponent implements OnInit, OnDestroy {
  @Input() isCollapsed = false;
  @Input() isMobile = false;
  @Output() collapsedChange = new EventEmitter<boolean>();

  navItems = NAV_ITEMS;
  bookId = '';
  currentPath = '';
  private sub!: Subscription;

  constructor(private route: ActivatedRoute, private router: Router) {}

  ngOnInit() {
    this.currentPath = this.router.url;
    this.bookId = this.route.snapshot.paramMap.get('bookId') || '';
    this.sub = this.router.events.pipe(filter(e => e instanceof NavigationEnd)).subscribe((e: any) => {
      this.currentPath = e.url;
    });
    // bookId is a param on THIS route (/:bookId), not on firstChild
    this.sub.add(this.route.params.subscribe(p => {
      this.bookId = p['bookId'] || '';
    }));
  }

  ngOnDestroy() { this.sub?.unsubscribe(); }

  setBookId(id: string) { this.bookId = id; }

  isActive(path: string): boolean {
    return this.currentPath.includes(`/${path}`);
  }

  toggleCollapse() {
    this.isCollapsed = !this.isCollapsed;
    this.collapsedChange.emit(this.isCollapsed);
  }
}

<aside class="sidebar" [class.collapsed]="isCollapsed && !isMobile">
  <!-- Desktop header -->
  <a routerLink="/" class="sidebar-header" *ngIf="!isMobile">
    <div class="sidebar-logo">E</div>
    <span class="sidebar-title" *ngIf="!isCollapsed">ExpenseTracker</span>
  </a>

  <!-- Nav items -->
  <nav class="sidebar-nav">
    <a
      *ngFor="let item of navItems"
      [routerLink]="'/' + bookId + '/' + item.path"
      class="nav-item"
      [class.active]="isActive(item.path)"
    >
      <span class="nav-icon" role="img" [attr.aria-label]="item.label">{{ item.icon }}</span>
      <span class="nav-label" *ngIf="!isCollapsed || isMobile">{{ item.label }}</span>
    </a>
  </nav>

  <!-- Collapse button (desktop only) -->
  <div class="sidebar-footer" *ngIf="!isMobile">
    <button class="collapse-btn" (click)="toggleCollapse()" [attr.aria-label]="isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'">
      {{ isCollapsed ? '→' : '←' }}
    </button>
  </div>
</aside>
